api_platform:
    eager_loading:
        enabled: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            enabled: false
            items_per_page: 20
            client_enabled: true #donner au client la possiblit√© de demander une pagination pendant la request
            client_items_per_page: true
            items_per_page_parameter_name: "count"
